"""Add company_info table

Revision ID: 7005c4490c5e
Revises: 006_app_settings
Create Date: 2026-01-28 14:25:28.969411+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7005c4490c5e'
down_revision: Union[str, None] = '006_app_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('tenant_id', sa.String(length=100), nullable=False, comment='Azure AD tenant ID for the organization'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Official company name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary contact email'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Contact phone number'),
    sa.Column('street_address', sa.Text(), nullable=True, comment='Street address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State/Province'),
    sa.Column('zip_code', sa.String(length=20), nullable=True, comment='Postal/ZIP code'),
    sa.Column('company_bio', sa.Text(), nullable=True, comment='Company description/about text'),
    sa.Column('relevant_experience', sa.Text(), nullable=True, comment='Description of past projects and relevant experience'),
    sa.Column('certifications', postgresql.ARRAY(sa.String(length=255)), nullable=False, comment='List of certifications held by the company'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_info_tenant_id'), 'company_info', ['tenant_id'], unique=True)
    op.drop_constraint(op.f('app_settings_key_key'), 'app_settings', type_='unique')
    op.alter_column('crawl_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_sessions', 'opportunities_new',
               existing_type=sa.INTEGER(),
               comment='New opportunities (not duplicates)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawl_sessions', 'opportunities_updated',
               existing_type=sa.INTEGER(),
               comment='Existing opportunities with updates',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawl_sessions', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of error details',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('crawl_sessions', 'triggered_by',
               existing_type=sa.VARCHAR(length=50),
               comment='How crawl was triggered: manual, scheduled, api',
               existing_nullable=False,
               existing_server_default=sa.text("'scheduler'::character varying"))
    op.alter_column('crawl_sessions', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Snapshot of source config at crawl time',
               existing_nullable=True)
    op.alter_column('crawl_sessions', 'progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Real-time progress data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_crawl_sessions_created_at'), table_name='crawl_sessions')
    op.alter_column('crawl_sources', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Crawler configuration: selectors, pagination, keywords, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crawl_sources', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Authentication configuration (credentials stored in Key Vault)',
               existing_nullable=True)
    op.alter_column('crawl_sources', 'schedule_cron',
               existing_type=sa.VARCHAR(length=50),
               comment="Cron expression for scheduled crawls (e.g., '0 6 * * *')",
               existing_nullable=True)
    op.alter_column('crawl_sources', 'crawl_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Delay between requests in seconds',
               existing_nullable=False,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('crawl_sources', 'priority',
               existing_type=sa.INTEGER(),
               comment='Crawl priority (1=highest, 10=lowest)',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('crawl_sources', 'last_crawl_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_success_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_crawl_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_crawl_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_crawl_sources_name'), 'crawl_sources', ['name'], unique=False)
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full AI analysis results'))
    op.add_column('documents', sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional document metadata'))
    op.add_column('documents', sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Is this the main RFP document?'))
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               comment='Path in SharePoint',
               existing_nullable=True)
    op.alter_column('documents', 'sharepoint_item_id',
               existing_type=sa.VARCHAR(length=100),
               comment='SharePoint item ID',
               existing_nullable=True)
    op.alter_column('documents', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('documents', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hash for deduplication',
               existing_nullable=True)
    op.alter_column('documents', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'extracted_text',
               existing_type=sa.TEXT(),
               comment='Text extracted from document',
               existing_nullable=True)
    op.alter_column('documents', 'ai_summary',
               existing_type=sa.TEXT(),
               comment='AI-generated document summary',
               existing_nullable=True)
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'downloaded_at')
    op.drop_column('documents', 'mime_type')
    op.alter_column('opportunities', 'source_opportunity_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Original opportunity ID from source system',
               existing_nullable=True)
    op.alter_column('opportunities', 'summary',
               existing_type=sa.TEXT(),
               comment='AI-generated summary',
               existing_nullable=True)
    op.alter_column('opportunities', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='AI-classified technology categories',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('opportunities', 'relevance_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='AI relevance score 0.00-1.00',
               existing_nullable=True)
    op.alter_column('opportunities', 'published_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('opportunities', 'submission_deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('opportunities', 'prequalification_deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('opportunities', 'is_discretionary',
               existing_type=sa.BOOLEAN(),
               comment='Small/discretionary purchase with simplified process',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'contact_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Contact name, email, phone',
               existing_nullable=True)
    op.alter_column('opportunities', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Original scraped data for debugging',
               existing_nullable=True)
    op.alter_column('opportunities', 'ai_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full AI analysis results',
               existing_nullable=True)
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_url'), table_name='opportunities')
    op.drop_constraint(op.f('uq_opportunities_source_opportunity_id'), 'opportunities', type_='unique')
    op.create_index(op.f('ix_opportunities_county'), 'opportunities', ['county'], unique=False)
    op.create_index(op.f('ix_opportunities_requires_prequalification'), 'opportunities', ['requires_prequalification'], unique=False)
    op.create_index(op.f('ix_opportunities_source_opportunity_id'), 'opportunities', ['source_opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.drop_column('opportunities', 'department')
    op.add_column('prequalification_requirements', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional requirement details'))
    op.alter_column('prequalification_requirements', 'requirement_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='Type: vendor_registration, certification, insurance, bond, etc.',
               existing_nullable=False)
    op.alter_column('prequalification_requirements', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Deadline for completing this requirement',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'registration_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               comment='URL to registration portal',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'portal_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of registration system (e.g., SAM.gov, State portal)',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'is_completed',
               existing_type=sa.BOOLEAN(),
               comment='Has MazikUSA completed this requirement?',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prequalification_requirements', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'ai_confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               comment='AI confidence in this detection (0.0-1.0)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prequalification_requirements', 'ai_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='AI confidence in this detection (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'is_completed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Has MazikUSA completed this requirement?',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prequalification_requirements', 'portal_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of registration system (e.g., SAM.gov, State portal)',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'registration_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to registration portal',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'deadline',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Deadline for completing this requirement',
               existing_nullable=True)
    op.alter_column('prequalification_requirements', 'requirement_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type: vendor_registration, certification, insurance, bond, etc.',
               existing_nullable=False)
    op.drop_column('prequalification_requirements', 'details')
    op.add_column('opportunities', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_opportunity_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_requires_prequalification'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_county'), table_name='opportunities')
    op.create_unique_constraint(op.f('uq_opportunities_source_opportunity_id'), 'opportunities', ['source_opportunity_id'])
    op.create_index(op.f('ix_opportunities_source_url'), 'opportunities', ['source_url'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.alter_column('opportunities', 'ai_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full AI analysis results',
               existing_nullable=True)
    op.alter_column('opportunities', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Original scraped data for debugging',
               existing_nullable=True)
    op.alter_column('opportunities', 'contact_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Contact name, email, phone',
               existing_nullable=True)
    op.alter_column('opportunities', 'is_discretionary',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Small/discretionary purchase with simplified process',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'prequalification_deadline',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('opportunities', 'submission_deadline',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('opportunities', 'published_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('opportunities', 'relevance_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='AI relevance score 0.00-1.00',
               existing_nullable=True)
    op.alter_column('opportunities', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='AI-classified technology categories',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('opportunities', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI-generated summary',
               existing_nullable=True)
    op.alter_column('opportunities', 'source_opportunity_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Original opportunity ID from source system',
               existing_nullable=True)
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('documents', 'ai_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI-generated document summary',
               existing_nullable=True)
    op.alter_column('documents', 'extracted_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Text extracted from document',
               existing_nullable=True)
    op.alter_column('documents', 'processed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hash for deduplication',
               existing_nullable=True)
    op.alter_column('documents', 'file_extension',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('documents', 'sharepoint_item_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='SharePoint item ID',
               existing_nullable=True)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Path in SharePoint',
               existing_nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'is_primary')
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'ai_analysis')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'content_type')
    op.drop_index(op.f('ix_crawl_sources_name'), table_name='crawl_sources')
    op.alter_column('crawl_sources', 'last_crawl_completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_crawl_started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_success_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'last_crawl_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_sources', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Crawl priority (1=highest, 10=lowest)',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('crawl_sources', 'crawl_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Delay between requests in seconds',
               existing_nullable=False,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('crawl_sources', 'schedule_cron',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Cron expression for scheduled crawls (e.g., '0 6 * * *')",
               existing_nullable=True)
    op.alter_column('crawl_sources', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Authentication configuration (credentials stored in Key Vault)',
               existing_nullable=True)
    op.alter_column('crawl_sources', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Crawler configuration: selectors, pagination, keywords, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_crawl_sessions_created_at'), 'crawl_sessions', ['created_at'], unique=False)
    op.alter_column('crawl_sessions', 'progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Real-time progress data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crawl_sessions', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Snapshot of source config at crawl time',
               existing_nullable=True)
    op.alter_column('crawl_sessions', 'triggered_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='How crawl was triggered: manual, scheduled, api',
               existing_nullable=False,
               existing_server_default=sa.text("'scheduler'::character varying"))
    op.alter_column('crawl_sessions', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of error details',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('crawl_sessions', 'opportunities_updated',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Existing opportunities with updates',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawl_sessions', 'opportunities_new',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='New opportunities (not duplicates)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawl_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_sessions', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('app_settings_key_key'), 'app_settings', ['key'])
    op.drop_index(op.f('ix_company_info_tenant_id'), table_name='company_info')
    op.drop_table('company_info')
    # ### end Alembic commands ###

